
// Generated by MaixHub

#define PARAM_CLASS_NUM 2
#define PARAM_LABELS {"hxt", "cgz"}
#define PARAM_MEAN 123.5
#define PARAM_STD  58.395
#define PARAM_INPUT_W 224
#define PARAM_INPUT_H 224
#define PARAM_INPUT_C 3
#define PARAM_OUTPUT_W 28
#define PARAM_OUTPUT_H 28
#define PARAM_OUTPUT_C 2

