
// Generated by MaixHub

#define PARAM_CLASS_NUM 4
#define PARAM_LABELS {"face0", "face1", "face2", "face3"}
#define PARAM_MEAN 123.5
#define PARAM_STD  58.395
#define PARAM_INPUT_W 64
#define PARAM_INPUT_H 64
#define PARAM_INPUT_C 3
#define PARAM_OUTPUT_W 1
#define PARAM_OUTPUT_H 1
#define PARAM_OUTPUT_C 4

