
// Generated by MaixHub

#define PARAM_CLASS_NUM 6
#define PARAM_LABELS {"face3", "Truman", "cgz", "face0", "face1", "face2"}
#define PARAM_MEAN 123.5
#define PARAM_STD  58.395
#define PARAM_INPUT_W 64
#define PARAM_INPUT_H 64
#define PARAM_INPUT_C 3
#define PARAM_OUTPUT_W 1
#define PARAM_OUTPUT_H 1
#define PARAM_OUTPUT_C 6

